"""Initial add header

Revision ID: 5eb32e65c2ee
Revises: 2d27a777f805
Create Date: 2018-02-11 21:47:28.232648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb32e65c2ee'
down_revision = '2d27a777f805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('header', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'header')
    # ### end Alembic commands ###
