""" chnaged header to title

Revision ID: 7e9410d0f942
Revises: 5eb32e65c2ee
Create Date: 2018-02-11 22:07:58.415826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9410d0f942'
down_revision = '5eb32e65c2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=150), nullable=True))
    op.drop_column('posts', 'header')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('header', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
